name: food_recommend
description: AI Food Decision Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Routing
  go_router: ^12.1.1
  go_router: ^12.1.3
  # State Management
  provider: ^6.0.5
  # HTTP & API
  http: ^1.1.0
  # Icons & UI
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  geolocator: ^14.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
